name: Vercel Non Prod Deployment With test
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on: 
  workflow_call:
  workflow_dispatch:
#   workflow_run:
#     workflows: ["Vercel Non Prod Deployment With test"]
#     types:
#       - completed
#   push:
#     branches-ignore:
#       - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Deployment URL Artifact
        uses: actions/download-artifact@v3
        with:
          name: deployment-url
          path: .
      - name: Read Deployment URL
        id: read-url
        run: echo "DEPLOYMENT_URL=$(cat deployment_url.txt)" >> $GITHUB_ENV
      - name: Install Dependencies
        run: npm install
      - name: Run Playwright E2E Tests
        run: npx playwright test --project=chromium --base-url=${{ env.DEPLOYMENT_URL }}
